[tool.poetry]
name = "foocat"
version = "0.1.0"
description = ""
authors = ["Shiying Wang <fsywang@alumni.ubc.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
